# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created: Wed Oct 14 01:47:55 2009
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(877, 836)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(10, 10, 851, 281))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.srcScrollArea = QtGui.QScrollArea(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcScrollArea.sizePolicy().hasHeightForWidth())
        self.srcScrollArea.setSizePolicy(sizePolicy)
        self.srcScrollArea.setWidgetResizable(True)
        self.srcScrollArea.setObjectName("srcScrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.srcScrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 418, 275))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.srcScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.comprScrollArea = QtGui.QScrollArea(self.splitter)
        self.comprScrollArea.setWidgetResizable(True)
        self.comprScrollArea.setObjectName("comprScrollArea")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget(self.comprScrollArea)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 418, 275))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.comprScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.teachW1ProgressBar = QtGui.QProgressBar(self.centralwidget)
        self.teachW1ProgressBar.setGeometry(QtCore.QRect(430, 300, 431, 23))
        self.teachW1ProgressBar.setProperty("value", QtCore.QVariant(24))
        self.teachW1ProgressBar.setObjectName("teachW1ProgressBar")
        self.teachW2ProgressBar = QtGui.QProgressBar(self.centralwidget)
        self.teachW2ProgressBar.setGeometry(QtCore.QRect(430, 330, 431, 23))
        self.teachW2ProgressBar.setProperty("value", QtCore.QVariant(24))
        self.teachW2ProgressBar.setObjectName("teachW2ProgressBar")
        self.teachButton = QtGui.QPushButton(self.centralwidget)
        self.teachButton.setGeometry(QtCore.QRect(210, 330, 114, 27))
        self.teachButton.setObjectName("teachButton")
        self.debugEdit = QtGui.QTextEdit(self.centralwidget)
        self.debugEdit.setGeometry(QtCore.QRect(10, 430, 851, 351))
        self.debugEdit.setObjectName("debugEdit")
        self.formLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 300, 101, 62))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.nEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.nEdit.setObjectName("nEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.nEdit)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.mEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.mEdit.setObjectName("mEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.mEdit)
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.formLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(130, 300, 81, 31))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.pEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.pEdit.setObjectName("pEdit")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.pEdit)
        self.adaptiveW1checkBox = QtGui.QCheckBox(self.centralwidget)
        self.adaptiveW1checkBox.setGeometry(QtCore.QRect(330, 300, 97, 23))
        self.adaptiveW1checkBox.setObjectName("adaptiveW1checkBox")
        self.adaptiveW2checkBox = QtGui.QCheckBox(self.centralwidget)
        self.adaptiveW2checkBox.setGeometry(QtCore.QRect(330, 330, 97, 23))
        self.adaptiveW2checkBox.setObjectName("adaptiveW2checkBox")
        self.formLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 370, 171, 52))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_4 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_4)
        self.maxIterationsSB = QtGui.QSpinBox(self.formLayoutWidget_3)
        self.maxIterationsSB.setMaximum(10000)
        self.maxIterationsSB.setProperty("value", QtCore.QVariant(40))
        self.maxIterationsSB.setObjectName("maxIterationsSB")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.maxIterationsSB)
        self.formLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(190, 370, 271, 52))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_5 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.comprLevelEdit = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.comprLevelEdit.setObjectName("comprLevelEdit")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.comprLevelEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 24))
        self.menubar.setObjectName("menubar")
        self.menuImage = QtGui.QMenu(self.menubar)
        self.menuImage.setObjectName("menuImage")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuImage.addAction(self.actionOpen)
        self.menubar.addAction(self.menuImage.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Compress neuron network", None, QtGui.QApplication.UnicodeUTF8))
        self.teachButton.setText(QtGui.QApplication.translate("MainWindow", "Teach", None, QtGui.QApplication.UnicodeUTF8))
        self.nEdit.setInputMask(QtGui.QApplication.translate("MainWindow", "000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "M:", None, QtGui.QApplication.UnicodeUTF8))
        self.mEdit.setInputMask(QtGui.QApplication.translate("MainWindow", "000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "N:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "P:", None, QtGui.QApplication.UnicodeUTF8))
        self.pEdit.setInputMask(QtGui.QApplication.translate("MainWindow", "000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.pEdit.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.adaptiveW1checkBox.setText(QtGui.QApplication.translate("MainWindow", "Adaptive?", None, QtGui.QApplication.UnicodeUTF8))
        self.adaptiveW2checkBox.setText(QtGui.QApplication.translate("MainWindow", "Adaptive?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Max teaching iterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Compression level:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuImage.setTitle(QtGui.QApplication.translate("MainWindow", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))

